<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="212" started-at="2020-04-12T08:31:32Z" finished-at="2020-04-12T08:31:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="212" started-at="2020-04-12T08:31:32Z" finished-at="2020-04-12T08:31:33Z">
      <class name="DatabaseTesting.ConnectMySQL">
        <test-method status="FAIL" signature="testDB()[pri:0, instance:DatabaseTesting.ConnectMySQL@29ee9faa]" name="testDB" duration-ms="147" started-at="2020-04-12T08:31:32Z" finished-at="2020-04-12T08:31:33Z">
          <exception class="java.sql.SQLException">
            <message>
              <![CDATA[Client does not support authentication protocol requested by server; consider upgrading MySQL client]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2847)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:750)
at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3558)
at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1151)
at com.mysql.jdbc.Connection.createNewIO(Connection.java:1768)
at com.mysql.jdbc.Connection.<init>(Connection.java:430)
at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:268)
at java.sql.DriverManager.getConnection(Unknown Source)
at java.sql.DriverManager.getConnection(Unknown Source)
at DatabaseTesting.ConnectMySQL.testDB(ConnectMySQL.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDB -->
      </class> <!-- DatabaseTesting.ConnectMySQL -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
